services:
  backend:
    build:
      context: .
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
  frontend:
    build:
      context: ./frontend
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
