version: '3'

services:
  frontend:
    container_name: replme-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: "unless-stopped"

  backend:
    container_name: replme-backend
    depends_on:
      - dind
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - docker-cert:/cert
      - replme-data:/data
      - devenvs-tmp:/devenvs
      - postgres-secret:/postgres
    environment:
      - DOCKER_CERT_PATH=/cert/client
      - DOCKER_TLS_VERIFY=true
      - GIN_MODE=release
      - REPL_LOG=debug
      - REPL_POSTGRES_URL=postgres://{user}:{secret}@replme-postgres:5432
      - REPL_POSTGRES_USER=postgres
      - REPL_POSTGRES_SECRET=/postgres/secret
      - REPL_IMG_TAG=ptwhy
      - REPL_API_KEY=/data/apikey
      - REPL_DEVENVS=/data/devenvs
      - REPL_DEVENVS_TMP=/devenvs
      - REPL_CONTAINER_LOGS=/data/logs
    restart: "unless-stopped"

  postgres:
    container_name: replme-postgres
    build:
      context: postgres
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-secret:/root/data
    restart: "unless-stopped"

  dind:
    image: docker:dind@sha256:5bf73daca1e5575772bdfd196a48cfeb6fd65f4affd2d83b42b16db36a2d2974
    container_name: replme-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    restart: "unless-stopped"
    # logging:
    #   driver: none
    ulimits:
      nproc: 79830
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - docker-cert:/certs
      - docker-data:/var/lib/docker
      - docker-app-data:/app/data/
      - devenvs-tmp:/devenvs

  nginx:
    container_name: replme-nginx
    depends_on:
      - backend
      - frontend
    image: nginx:alpine@sha256:a45ee5d042aaa9e81e013f97ae40c3dda26fbe98f22b6251acdf28e579560d55
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/replme.conf
    ports:
      - 6969:6969
    restart: "unless-stopped"


volumes:
  replme-data:
  postgres-data:
  postgres-secret:
  devenvs-tmp:
  docker-cert:
  docker-data:
  docker-app-data:

