version: '3'
services:
  wonki:
    build: .
    depends_on:
      - wonki-postgres
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    # Define the port mapping (external:internal port)
    ports:
      - "2027:2027"
    restart: always
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
  
  wonki-postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: verysecurepw
      POSTGRES_DB: wonki-db
      PGDATA: /data/postgres
    # The code should be copied into the container using COPY.
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    command: postgres -c 'max_connections=2048'
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
    