version: '3'
services:
  proxy:
    build:
      context: ./proxy/
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
  web:
    build:
      context: ./web/
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
  echo:
    build:
      context: ./echo/
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
  premium-forum:
    build:
      context: ./forum/
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
  open-forum:
    build:
      context: ./forum/
      args:
        http_proxy: http://proxy.prod.bambi.ovh:3128
        https_proxy: http://proxy.prod.bambi.ovh:3128
        HTTP_PROXY: http://proxy.prod.bambi.ovh:3128
        HTTPS_PROXY: http://proxy.prod.bambi.ovh:3128
